# Generated by Django 5.0.3 on 2024-04-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactsubmission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Registration',
        ),
    ]
